### ISSUE TITLE
How to add media="all" to <link> tag

### ISSUE THREAD

**Issue by aurelien-w** [widmogrod/zf2-assetic-module#129] opened 2015-04-27 14:35 UTC
Hello,

How can I change the attribute media="sceen " to media="all" ?
In the configuration file ?

```php
<!-- Style -->
<?php echo $this->plugin('HeadStyle'); ?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath().'/img/favicon.ico')); ?>
```

```php
'modules' => array(
        'application' => array(
            'root_path' => __DIR__ . '/../assets',
            'collections' => array(
                'head_css' => array(
                    'assets' => array(
                        'css/bootstrap.min.css',
                        'css/style.css',
                    ),
                    'filters' => array(
                        'CssRewriteFilter' => array(
                            'name' => 'Assetic\Filter\CssRewriteFilter'
                        ),
                    ),
                ),
            ),
        ),
    ),
```

Thank you

**Comment by widmogrod** [comment] 2015-04-28 21:52
Duplicate of #125

**Closed by widmogrod** 2015-04-28 21:52 UTC
